! Generated by cart. DO NOT EDIT
program main
    use caffeine_m, only : caf_error_stop
    implicit none

    if (.not.run()) call caf_error_stop()
contains
    function run() result(passed)
        use t_cell_collection_test, only: &
                t_cell_collection_t_cell_collection => &
                    test_t_cell_collection
        use garden , only: test_item_t, test_that, run_tests
        use setup_and_teardown, only: setup
        use setup_and_teardown, only: teardown

        logical :: passed

        type(test_item_t) :: tests
        type(test_item_t) :: individual_tests(1)

        individual_tests(1) = t_cell_collection_t_cell_collection()
        tests = test_that(individual_tests)

        call setup
        passed = run_tests(tests)
        call teardown
    end function
end program
