! Copyright (c), The Regents of the University of California
! Terms of use are as specified in LICENSE.txt
! Generated by cart. DO NOT EDIT
program main
    implicit none

    if (.not.run()) stop 1
contains
    function run() result(passed)
        use t_cell_collection_test, only: &
                t_cell_collection_t_cell_collection => &
                    test_t_cell_collection
        use garden, only: test_item_t, test_that, run_tests

        logical :: passed

        type(test_item_t) :: tests
        type(test_item_t) :: individual_tests(1)

        individual_tests(1) = t_cell_collection_t_cell_collection()
        tests = test_that(individual_tests)


        passed = run_tests(tests)

    end function
end program
