name = "matcha"

[build]
link = ["caffeine", "gasnet-smp-seq", "pmi2", "hugetlbfs", "m"]

[dependencies]
assert = {git = "https://github.com/BerkeleyLab/assert.git", tag = "2.1.2"}
julienne = {git = "https://github.com/BerkeleyLab/julienne", tag = "2.4.0"}
