name = "matcha"
version = "0.1.0"
license = "see LICENSE.txt"
author = "Damian Rouson, David Torres,  Dominick Martinez, Jeremiah Bailey, and Brad Richardson"
maintainer = "rouson@lbl.gov"

[dependencies]
assert = {git = "https://github.com/berkeleylab/assert", tag = "2.1.0"}
julienne = {git = "https://github.com/BerkeleyLab/julienne", tag = "1.8.3"}
sourcery = {git = "https://github.com/sourceryinstitute/sourcery", tag = "4.5.1"}
