name = "matcha"
version = "0.1.0"
license = "see LICENSE.txt"
author = "Damian Rouson, David Torres,  Dominick Martinez, Jeremiah Bailey, and Brad Richardson"
maintainer = "rouson@lbl.gov"

[[executable]]
name = "matcha"
source-dir="app"
main = "main.F90"

[dependencies]
assert = {git = "https://github.com/sourceryinstitute/assert", tag = "1.4.0"}
sourcery = {git = "https://github.com/sourceryinstitute/sourcery", tag = "3.8.0"}
