name = "matcha"
version = "0.1.0"
license = "license"
author = "David Torres, Damian Rouson, Dominick Martinez, and Jeremiah Bailey"
maintainer = "davytorres@nnmc.edu"
copyright = "Copyright 2022, David Torres"

[dev-dependencies]
garden = {git = "https://gitlab.com/everythingfunctional/garden", tag = "v1.0.3"}
