@startuml

class input_t {
  - num_cells_ : integer 
  - num_positions_ : integer 
  - num_dimensions_ : integer 
  - num_intervals_ : integer
  - time_step_ : double precision
  + num_cells() : integer
  + num_positions() : integer
  + num_dimensions() : integer
  + num_intervals() : integer
  + time_step() : double precision
  + input_t() : input_t
}

@enduml
