@startuml

class t_cell_collection_t{
  - positions_ : double precision[:,:]
  - time_ : double precision
  + positions() : double precision[:,:]
  + time() : double precision
  + t_cell_collection_t(positions : double precision[:,:], time : double precision) : t_cell_collection_t
}

note left of t_cell_collection_t::positions()
  context t_cell_collection_t::positions() pre: allocated(postions_)
end note

@enduml
