matcha – Matcha
matcha Module Procedure
36 statements
Source File
module procedure matcha module function matcha(input) result(history) Interface →
Arguments
Type Intent Optional Attributes Name
type(input_t), intent(in) :: input
Return Value type(t_cell_collection_t), allocatable, (:)
Calls
Call graph
matcha calls bin_t, first, num_cells, num_dimensions, num_intervals, num_positions, positions, sample_distribution, time_step, last, random_4vectors, random_init, random_positions, velocities