simulated_distribution – Matcha
simulated_distribution Interface
12 statements
Source File
interface
Calls
private module module function simulated_distribution(self) result(output_distribution) Implementation →
Arguments
Type Intent Optional Attributes Name
class(output_t), intent(in) :: self
Return Value double precision,allocatable,(:,:)
Description
The result is a histogram calculated from the simulation output
Call graph
simulated_distribution calls simulated_distribution, do_concurrent_speeds, do_concurrent_k, emp_distribution, do_concurrent_output_distribution
do_concurrent_speeds calls do_concurrent_speeds, u
do_concurrent_k calls do_concurrent_k
do_concurrent_output_distribution calls do_concurrent_output_distribution