velocities – Matcha
velocities Interface
13 statements
Source File
interface
Calls
private pure module module function velocities(self, speeds, directions) result(my_velocities) Implementation →
Arguments
Type Intent Optional Attributes Name
class(distribution_t), intent(in) :: self
double precision, intent(in) :: speeds(:,:)
double precision, intent(in) :: directions(:,:,:)
Return Value double precision,allocatable,(:,:,:)
Description
Return the t_cell_collection_t object's velocity vectors
Call graph
velocities calls velocities, assert, do_concurrent_sampled_speeds, do_concurrent_my_velocities
do_concurrent_sampled_speeds calls do_concurrent_sampled_speeds
do_concurrent_my_velocities calls do_concurrent_my_velocities