name = "matcha"
version = "0.1.0"
license = "see LICENSE.txt"
author = "Damian Rouson, David Torres,  Dominick Martinez, Jeremiah Bailey, and Brad Richardson"
maintainer = "rouson@lbl.gov"

[dependencies]
assert = {git = "https://github.com/sourceryinstitute/assert", rev = "a3065a9dffaedf085fbd262c6bf31b309aa43a4a"}
sourcery = {path = "vendor/sourcery"}
caffeine = {path = "build/dependencies/caffeine"}

[dev-dependencies]
garden = {path = "vendor/garden"}
