name: Build and Deploy Documentation

on: [push, pull_request]


jobs:
  Build:
    runs-on: ubuntu-latest

    env:
      FC: gfortran
      GCC_V: 14

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Dependencies Ubuntu
      run: |
        sudo apt-get update
        sudo apt install -y gfortran-${GCC_V} python3-dev python3 build-essential numdiff graphviz
        sudo pip install ford markdown
        echo "---------"
        gfortran --version
        echo "---------"
    - name: Build Developer Documenation
      run: |
        # Turn warnings into errors
        ford ford.md > ford_output.txt
        cat ford_output.txt; if grep -q -i Warning ford_output.txt; then exit 1; fi
        cp ./README.md ./doc/html
    - name: Upload Documentation
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: doc/html
        if-no-files-found: error

    - name: Broken Link Check
      if: ${{ github.ref == 'refs/heads/main'}}
      uses: technote-space/broken-link-checker-action@v1
      with:
        TARGET: file://${{ github.workspace }}/doc/html/index.html
        RECURSIVE: true
        ASSIGNEES: ${{ github.actor }}

    - name: Deploy API Documentation
      uses: JamesIves/github-pages-deploy-action@4.1.0
      if: ${{ github.event_name == 'push'  &&  github.ref == 'refs/heads/main' }}
      with:
        branch: gh-pages
        folder: doc/html
